### ISSUE TITLE
4 arms possible

### ISSUE THREAD

**Issue by maierei** [moucha19/OpenSCAD-Fletching-jig#10]
Hello,
would it be possible to get a version with 4 arms to e able to use 4 vanes?

Thanks
Markus

**Comment by moucha19** [comment]
Hi,
thanks for the push to finally add this feature :smile:. In the development branch, I added a new parameter `vane_count` that you can play with until new version is released. 
![obrazek](https://github.com/user-attachments/assets/4111c6e0-634b-4d39-9cd6-7395258f7fb3)

**Comment by maierei** [comment]
Hi Petr,
great - works like a charm - I will print the first test tomorrow and then try it on my new arrows - thanks again!

Markus

**Comment by moucha19** [comment]
New version that supports 4 vanes was [released](https://github.com/moucha19/OpenSCAD-Fletching-jig/releases/tag/v2.0).
